# Generated by Django 2.2 on 2021-05-05 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerstext', models.CharField(max_length=255, verbose_name='Ответ для вопроса')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontext', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('countanswers', models.PositiveIntegerField(verbose_name='Кол-во ответор для вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_options', to='question.Answers', verbose_name='Ответ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика опросов',
                'verbose_name_plural': 'Статистика опроса',
                'db_table': 'statistic',
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepolls', models.CharField(max_length=255, verbose_name='Название опроса')),
                ('datestart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала опроса')),
                ('dateend', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата конца опроса')),
                ('descriptions', models.TextField(null=True, verbose_name='Описание опроса')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'polls',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Question', verbose_name='Вопрос'),
        ),
    ]
