# Generated by Django 2.2 on 2021-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='countanswersmaxсhoice',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во ответор для вопроса'),
        ),
    ]
