# Generated by Django 2.2 on 2021-05-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_countanswersmaxсhoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.Polls', verbose_name='Вопрос'),
        ),
    ]
